const menu=[
{cat:'Cookies',name:'Classic Chocolate Chip',price:3.25,desc:'Soft, thick and full of chocolate chips.',badge:'Best Seller'},{cat:'Cookies',name:'Biscoff Cookie Butter',price:3.25,desc:'Cookie butter flavor with sweet bakery crunch.',badge:'Popular'},{cat:'Cookies',name:'Nutella Lava',price:3.50,desc:'Chocolate cookie with Nutella-style filling.',badge:'Filled'},{cat:'Cookies',name:'S’mores',price:3.50,desc:'Graham, marshmallow and chocolate inspired.',badge:'Campfire'},{cat:'Cookies',name:'Strawberry Crunch',price:3.25,desc:'Sweet strawberry crunch cookie.',badge:'Pink Favorite'},{cat:'Cookies',name:'Red Velvet White Chocolate',price:3.25,desc:'Red velvet cookie with white chocolate.',badge:'Classic'},{cat:'Cookies',name:'Brown Butter Pecan',price:3.50,desc:'Rich brown butter pecan cookie.',badge:'Nutty'},{cat:'Cookies',name:'Cookie Monster',price:3.25,desc:'Fun blue cookie loaded with sweets.',badge:'Fun'},{cat:'Cookies',name:'Lemon Sugar',price:3.25,desc:'Bright lemon sugar cookie.',badge:'Fresh'},
{cat:'Cupcakes',name:'Vanilla Bean',price:3.25,desc:'Classic vanilla cupcake.',badge:'Classic'},{cat:'Cupcakes',name:'Chocolate Fudge',price:3.25,desc:'Rich chocolate cupcake.',badge:'Chocolate'},{cat:'Cupcakes',name:'Strawberry Crunch',price:3.50,desc:'Pink strawberry crunch cupcake.',badge:'Popular'},{cat:'Cupcakes',name:'Biscoff Dream',price:3.50,desc:'Biscoff flavored cupcake.',badge:'Dreamy'},{cat:'Cupcakes',name:'Nutella Hazelnut',price:3.75,desc:'Chocolate hazelnut cupcake.',badge:'Premium'},{cat:'Cupcakes',name:'Banana Pudding',price:3.75,desc:'Banana pudding inspired cupcake.',badge:'Southern'},{cat:'Cupcakes',name:'Red Velvet',price:3.75,desc:'Red velvet cupcake.',badge:'Classic'},
{cat:'Brownies & Bars',name:'Classic Fudge',price:3.25,desc:'Rich, fudgy brownie.',badge:'Fudgy'},{cat:'Brownies & Bars',name:'Nutella Swirl',price:3.25,desc:'Brownie with chocolate hazelnut swirl.',badge:'Swirl'},{cat:'Brownies & Bars',name:'Biscoff Brownies',price:3.25,desc:'Brownies with Biscoff flavor.',badge:'Popular'},{cat:'Brownies & Bars',name:'Oreo Cheesecake Brownies',price:3.25,desc:'Oreo cheesecake brownie bar.',badge:'Creamy'},{cat:'Brownies & Bars',name:'Turtle Brownies',price:3.25,desc:'Chocolate, caramel and pecan style brownie.',badge:'Caramel'},
{cat:'Cinnamon Rolls',name:'Classic Glazed',price:3.25,desc:'Soft glazed cinnamon roll.',badge:'Classic'},{cat:'Cinnamon Rolls',name:'Biscoff Drizzle',price:3.75,desc:'Cinnamon roll with Biscoff drizzle.',badge:'Drizzle'},{cat:'Cinnamon Rolls',name:'Nutella Hazelnut',price:3.75,desc:'Sweet hazelnut chocolate roll.',badge:'Premium'},{cat:'Cinnamon Rolls',name:'Strawberry Cheesecake',price:4.00,desc:'Strawberry cheesecake cinnamon roll.',badge:'Sweet'},{cat:'Cinnamon Rolls',name:'Cookies & Cream',price:4.50,desc:'Cookies and cream topped roll.',badge:'Loaded'},{cat:'Cinnamon Rolls',name:'Sugar Cheesecake',price:4.50,desc:'Sweet cheesecake inspired roll.',badge:'Loaded'},
{cat:'Mini Cakes',name:'Chocolate Luxe',price:8.99,desc:'Personal mini cake.',badge:'Personal'},{cat:'Mini Cakes',name:'Strawberry Shortcake',price:10.99,desc:'Personal strawberry mini cake.',badge:'Premium'},{cat:'Mini Cakes',name:'Biscoff Crunch',price:10.99,desc:'Personal Biscoff mini cake.',badge:'Premium'},{cat:'Mini Cakes',name:'Lemon Cake',price:8.99,desc:'Personal lemon mini cake.',badge:'Fresh'},{cat:'Mini Cakes',name:'Nutella Dream',price:8.99,desc:'Personal Nutella mini cake.',badge:'Dreamy'},{cat:'Mini Cakes',name:'Confetti Cake',price:8.99,desc:'Personal confetti mini cake.',badge:'Birthday'},
{cat:'Breads',name:'White Bread',price:7.99,desc:'Fresh baked loaf.',badge:'Loaf'},{cat:'Breads',name:'Honey Butter Bread',price:9.99,desc:'Soft honey butter loaf.',badge:'Sweet'},{cat:'Breads',name:'Garlic Herb Bread',price:9.99,desc:'Savory garlic herb loaf.',badge:'Savory'},{cat:'Breads',name:'Chocolate Chip Banana Bread',price:11.99,desc:'Banana bread with chocolate chips.',badge:'Popular'},{cat:'Breads',name:'Cinnamon Swirl Bread',price:11.99,desc:'Sweet cinnamon swirl loaf.',badge:'Swirl'},{cat:'Pull-Apart Breads',name:'Cinnamon Sugar Pull-Apart',price:17.99,desc:'Sweet pull-apart bread.',badge:'Shareable'},{cat:'Pull-Apart Breads',name:'Garlic Parmesan Pull-Apart',price:19.99,desc:'Savory pull-apart bread.',badge:'Savory'},{cat:'Pull-Apart Breads',name:'Pizza Bread',price:19.99,desc:'Savory pizza-style pull-apart.',badge:'Party'},
{cat:'Extras',name:'Chocolate Drizzle',price:.69,desc:'Add-on drizzle.',badge:'Add-on'},{cat:'Extras',name:'Nutella Drizzle',price:.69,desc:'Add-on drizzle.',badge:'Add-on'},{cat:'Extras',name:'Oreo Crumble',price:.69,desc:'Add-on topping.',badge:'Add-on'},{cat:'Extras',name:'Extra Filling',price:.69,desc:'Additional filling per item.',badge:'Add-on'}
];
let cart=JSON.parse(localStorage.getItem('sst_cart_final')||'[]');
let orders=JSON.parse(localStorage.getItem('sst_orders_final')||'[]');
let activeCat='All';
const money=n=>'$'+Number(n||0).toFixed(2);
const cats=['All',...new Set(menu.map(x=>x.cat))];
function init(){document.getElementById('categoryTabs').innerHTML=cats.map(c=>`<button class="${c===activeCat?'active':''}" onclick="setCat('${c}')">${c}</button>`).join('');renderMenu();renderCart();renderAdmin();setMinDate();}
function setMinDate(){const d=document.querySelector('input[type="date"]'); if(d&&!d.min)d.min=new Date().toISOString().slice(0,10)}
function toggleMenu(){document.getElementById('navLinks').classList.toggle('show')}
function setCat(c){activeCat=c;renderCategoryButtons();renderMenu()}
function renderCategoryButtons(){document.getElementById('categoryTabs').innerHTML=cats.map(c=>`<button class="${c===activeCat?'active':''}" onclick="setCat('${c}')">${c}</button>`).join('')}
function renderMenu(){let q=(document.getElementById('searchBox')?.value||'').toLowerCase();let sort=document.getElementById('sortBox')?.value||'featured';let items=activeCat==='All'?menu:[...menu].filter(x=>x.cat===activeCat);items=items.filter(x=>(x.name+x.desc+x.cat).toLowerCase().includes(q));if(sort==='low')items.sort((a,b)=>a.price-b.price);if(sort==='high')items.sort((a,b)=>b.price-a.price);document.getElementById('menuGrid').innerHTML=items.length?items.map(p=>`<div class="product"><div class="add-row"><span>${p.badge}</span><span>${p.cat}</span></div><h3>${p.name}</h3><small>${p.desc}</small><div class="price">${money(p.price)}</div><button class="btn primary full" onclick="addToCart('${escapeName(p.name)}')">Add to Cart</button></div>`).join(''):'<p>No items found. Try another search.</p>'}
function escapeName(s){return s.replace(/'/g,"\\'")}
function addToCart(name){let p=menu.find(x=>x.name===name), item=cart.find(x=>x.name===name); if(item)item.qty++; else cart.push({...p,qty:1}); saveCart(); toggleCart(true)}
function changeQty(name,d){let item=cart.find(x=>x.name===name); if(!item)return; item.qty+=d; if(item.qty<=0)cart=cart.filter(x=>x.name!==name); saveCart()}
function saveCart(){localStorage.setItem('sst_cart_final',JSON.stringify(cart));renderCart()}
function subtotal(){return cart.reduce((s,x)=>s+x.price*x.qty,0)}
function deliveryFee(){let type=document.getElementById('orderType')?.value; let m=Number(document.getElementById('miles')?.value||0); if(type!=='Local Delivery')return 0; if(m<=5)return 5;if(m<=10)return 8;if(m<=15)return 10;if(m<=20)return 15;return 0}
function total(){return subtotal()+deliveryFee()}
function renderCart(){const count=cart.reduce((s,x)=>s+x.qty,0);document.getElementById('cartCount').textContent=count;document.getElementById('cartItems').innerHTML=cart.length?cart.map(x=>`<div class="cart-item"><b>${x.name}</b><br><small>${money(x.price)} each</small><div class="qty"><button onclick="changeQty('${escapeName(x.name)}',-1)">-</button><span>${x.qty}</span><button onclick="changeQty('${escapeName(x.name)}',1)">+</button><strong>${money(x.price*x.qty)}</strong></div></div>`).join(''):'<p>Your cart is empty. Add treats from the menu.</p>';document.getElementById('cartSubtotal').textContent=money(subtotal());document.getElementById('cartDelivery').textContent=money(deliveryFee());document.getElementById('cartTotal').textContent=money(total());const co=document.getElementById('checkoutTotal');if(co)co.textContent=money(total())}
function toggleCart(force){let open=force===undefined?!document.getElementById('cartPanel').classList.contains('open'):force;document.getElementById('cartPanel').classList.toggle('open',open);document.getElementById('overlay').classList.toggle('show',open)}
function updateDeliveryFields(){let show=document.getElementById('orderType').value!=='Pickup';document.getElementById('deliveryFields').classList.toggle('hidden',!show);renderCart()}
function submitOrder(e){e.preventDefault();if(!cart.length){alert('Please add at least one item to the cart.');return}let data=Object.fromEntries(new FormData(e.target).entries());let order={id:'SST-'+Date.now().toString().slice(-6),created:new Date().toLocaleString(),customer:data,items:[...cart],subtotal:subtotal(),delivery:deliveryFee(),total:total(),status:'Order Received'};orders.unshift(order);localStorage.setItem('sst_orders_final',JSON.stringify(orders));cart=[];saveCart();renderAdmin();let summary=order.items.map(x=>`${x.qty} x ${x.name}`).join(', ');let msg=`Thank you ${data.name}! Your Share's Sweet Treats order ${order.id} was received. Total: ${money(order.total)}. Items: ${summary}.`;let email=`mailto:${encodeURIComponent(data.email)}?subject=${encodeURIComponent('Thank you for your Share\'s Sweet Treats order 💗')}&body=${encodeURIComponent(msg+'\n\nMade with love, baked fresh. Thank you for supporting my small business!')}`;let sms=`sms:${data.phone}?&body=${encodeURIComponent(msg)}`;document.getElementById('confirmation').classList.remove('hidden');document.getElementById('confirmation').innerHTML=`<h3>Order request received 💗</h3><p><b>Order:</b> ${order.id}</p><p>${msg}</p><p><a class="btn secondary" href="${email}">Send thank-you email</a> <a class="btn secondary" href="${sms}">Send thank-you text</a></p><p class="note">Launch note: for automatic sending, connect EmailJS/Formspree for email and Twilio for SMS.</p>`;e.target.reset();updateDeliveryFields();location.hash='confirmation'}
function renderAdmin(){const revenue=orders.reduce((s,o)=>s+Number(o.total),0);document.getElementById('adminOrders').textContent=orders.length;document.getElementById('adminRevenue').textContent=money(revenue);document.getElementById('adminCustomers').textContent=new Set(orders.map(o=>o.customer.email)).size;document.getElementById('adminAverage').textContent=money(orders.length?revenue/orders.length:0);document.getElementById('ordersList').innerHTML=orders.length?orders.map(o=>`<div class="order-card"><b>${o.id} • ${o.customer.name} • ${money(o.total)}</b><p>${o.items.map(i=>i.qty+' x '+i.name).join(', ')}</p><small>${o.customer.orderType} • ${o.customer.phone} • ${o.status} • ${o.created}</small><br><small>${o.customer.address||''}</small></div>`).join(''):'<p>No test orders yet. Place a sample order to test the flow.</p>'}
function exportOrders(){if(!orders.length){alert('No orders to export yet.');return}const rows=[['Order ID','Date','Customer','Email','Phone','Order Type','Items','Subtotal','Delivery','Total','Status']];orders.forEach(o=>rows.push([o.id,o.created,o.customer.name,o.customer.email,o.customer.phone,o.customer.orderType,o.items.map(i=>`${i.qty} x ${i.name}`).join('; '),o.subtotal,o.delivery,o.total,o.status]));const csv=rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='shares-sweet-treats-orders.csv';a.click()}
function clearOrders(){if(confirm('Clear test orders from this browser?')){orders=[];localStorage.setItem('sst_orders_final','[]');renderAdmin()}}
init();
